sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: imYFXsxYdPBod2ycRrpjn/0da4EKHrIlNal0ZCsjOEvCBuMr9tqUVQbVsEPWDkPIlqHyN7mQtXND5IFGFneYTtfzpCyN+56nqhbgL1wHaZGGMprzQ7H7iAWYDpmWtrKOFy++mq9WtLjc4P+M8HGRFRyE0LGUbxdw+SJQBsJAz+Wzrldde62FboXJyJfl620MDjDrAwBSrnkAP9uA3oNw+nXEyALTkqC+1o2ucWCFMLK0QKXL2xm5+Et5vt7T5Q5ZjP2pWuL5IM2qf0mlbd6HpbPG9YZwlCoCs/+UdcS471nNZkhaImQVjVw0n1OBde05M977+LayLCL5R1GqP8QJi2Jc0amtTV8QsIkvhCvmvrRA/ztGYqhsIWPBJvWlgeJe7BKt52gEXAIwy4b3j+wJNjfhSTkhYP0VrvVbKcbPBwSSyJm/UxrftFm9DarFqHCykG7ZESm6Rzi6OfuFPDkDSajEQpHSLznY7KXc+nT89Q7QOBSJ3nr0GeXuNA6nYelK2hv5IzEJYJiGcKT3qE9j8ROXJibKhLLHk8AEI2id9Dk1UyA1bP7WfB6igVwLeRPvy2JI3XkyNmDTyszJHKOYYCMC/AQ94PzYfbJP2H2eQr6bCs4TRx/xVdnhfAEvmI+ZfO2rXaQw+9tMrhs2M2X/IebNHOUKCs7c6pXZ1Vg6PA8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Long-Odds_2730
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy